output_dir: path/to/output_dir
checkpoint: path/to/checkpoint
dataset:
  class: td_datasets.EnzymeCommission # td_datasets.EnzymeCommission / GeneOntology
  path: path/to/protst-datasets
  branch: null # EC: null; GO_MF: MF; GO_CC: CC; GO_BP: BP
  test_cutoff: 0.95
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: residue
      - class: TruncateProtein
        max_length: 550

task:
  class: MultipleBinaryClassification
  model:
    class: ProtAC
    path: path/to/esm-model-weights/
    model: PB_tiny
    mask_modeling: False
    output_dim: 512
    readout: mean
    use_proj: True
  criterion: bce
  metric: [ 'auprc@micro', 'f1_max' ]
  num_mlp_layer: 2

optimizer:
  class: AdamW
  lr: 5.0e-3

# scheduler:
#   class: WarmupLR
#   warm_lr: 1.0e-5
#   warm_epoch: 10
#   min_lr: 5.0e-5 #5e-4

engine:
  gpus: [0, 1, 2, 3, 4, 5, 6, 7]
  batch_size: 64
  log_interval: 1000

lr_ratio: 0.2

eval_metric: f1_max

train:
  num_epoch: 100

fix_encoder: True
